# Generated by Django 4.2.3 on 2023-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=30)),
                ('horario_funcionamiento', models.CharField(max_length=30)),
            ],
        ),
    ]
